---
name: test
permissions:
  contents: read
"on":
  push:
    branches: "main"
jobs:
  test:
    concurrency:
      # yamllint disable-line
      group: test # You can specify a group name for concurrency control
      # yamllint disable-line
      cancel-in-progress: true # This will cancel any in-progress runs in the
      # same group
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run tests
        run: go test ./...
        timeout-minutes: 15
